#sudo docker build -t mnbase . -f Dockerfile.mnbase
FROM ubuntu:latest

# Install required tools
RUN apt-get update && apt-get install -y \
    net-tools \
    lldpd \
    netcat \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Entrypoint to keep container running
CMD ["tail", "-f", "/dev/null"]
